# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('num', models.IntegerField()),
                ('status', models.IntegerField()),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Though',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETD', models.TimeField()),
                ('ETA', models.TimeField()),
                ('order', models.IntegerField()),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Line')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=20)),
                ('is_stu', models.BooleanField()),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Line')),
                ('order_id', models.ManyToManyField(to='ticket.Order')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Route')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Seat')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='departure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre', to='ticket.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='ticket.Station'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ManyToManyField(to='ticket.User'),
        ),
    ]
